export const siteConfig = {
  name: "Sendport",
  legalName: "Sendport Technologies Inc.",
  tagline: "The Developer-First Email Delivery & Transactional API Platform",
  description: "Sendport is the ultra-fast, high-deliverability email API built for modern developers. 2048-bit RSA DKIM, dynamic templates, live open/click tracking, and instant SMTP relay.",
  url: process.env.NEXT_PUBLIC_APP_URL || "https://getsendport.com",
  domain: "getsendport.com",
  founder: {
    name: "Muhammad Umar",
    role: "Founder & Lead Architect",
  },
  supportEmail: "support@getsendport.com",
  social: {
    twitter: "https://twitter.com/getsendport",
    github: "https://github.com/sendport/sendport",
    linkedin: "https://linkedin.com/company/sendport",
  },
  stats: {
    uptime: "99.99%",
    avgLatency: "8.4ms",
    deliverability: "99.98%",
    emailsDelivered: "50M+",
    activeSenders: "12,000+",
  },
  pricingTiers: [
    {
      id: "STARTER",
      name: "Starter",
      badge: "Free Forever",
      description: "Perfect for indie hackers, hobbyists, and side projects.",
      price: {
        USD: 0,
        EUR: 0,
        GBP: 0,
        AED: 0,
        SAR: 0,
        PKR: 0,
      },
      dailyLimit: "100 emails / day",
      monthlyLimit: "3,000 / month",
      features: [
        "1 Verified Sending Domain",
        "2048-bit RSA DKIM Signing",
        "Developer REST API & SDKs",
        "Instant SMTP Relay (Port 587/465)",
        "Realtime Open & Click Tracking",
        "3 Days Log Retention",
        "Community Support",
      ],
      popular: false,
      cta: "Get Started Free",
    },
    {
      id: "GROWTH",
      name: "Growth",
      badge: "Most Popular",
      description: "Ideal for growing SaaS apps, startups, and e-commerce stores.",
      price: {
        USD: 20,
        EUR: 19,
        GBP: 16,
        AED: 75,
        SAR: 75,
        PKR: 5500,
      },
      dailyLimit: "3,000 emails / day",
      monthlyLimit: "90,000 / month",
      features: [
        "Up to 5 Verified Custom Domains",
        "Automated 30-Day Domain Warmup",
        "AI Email Spam Optimizer",
        "Visual Template Builder & {{tags}}",
        "Inbound Webhook Routing",
        "Smart Bounce Classifier (Hard/Soft)",
        "30 Days Log Retention",
        "Priority 24/7 Email Support",
      ],
      popular: true,
      cta: "Start 14-Day Pro Trial",
    },
    {
      id: "SCALE_PRO",
      name: "Scale Pro",
      badge: "Enterprise Grade",
      description: "For high-volume senders, marketing agencies, and global platforms.",
      price: {
        USD: 79,
        EUR: 74,
        GBP: 62,
        AED: 290,
        SAR: 295,
        PKR: 22100,
      },
      dailyLimit: "25,000 emails / day",
      monthlyLimit: "750,000 / month",
      features: [
        "Dedicated Clean IP Address",
        "Sub-10ms Global Priority Queue",
        "A/B Testing Variant Splitter",
        "Multi-Tenant Team Workspaces (RBAC)",
        "Realtime Webhooks (HMAC-SHA256)",
        "Full Security Audit Trail & 2FA",
        "90 Days Log Retention",
        "Dedicated Deliverability Specialist",
      ],
      popular: false,
      cta: "Upgrade to Scale Pro",
    },
  ],
};
